"""Add stock_level to medicine table

Revision ID: 1d2f177fc44e
Revises: 9ec75900aacd
Create Date: 2025-12-20 00:27:15.089151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2f177fc44e'
down_revision = '9ec75900aacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_level', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_column('stock_level')

    # ### end Alembic commands ###
