"""Create district-based medicine structure

Revision ID: 6846b65a5b25
Revises: 71bc2434bdfe
Create Date: 2025-12-17 00:07:24.731675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6846b65a5b25'
down_revision = '71bc2434bdfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('area_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_code')
    )
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_name'), ['name'], unique=True)

    op.create_table('formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('therapeutic_class', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formula', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formula_name'), ['name'], unique=True)

    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('medicine_id', sa.String(length=50), nullable=False),
    sa.Column('dosage_strength', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formula.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id')
    )
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_formula_id'), ['formula_id'], unique=False)

    op.create_table('medicine_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecasted_quantity', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine_forecast', schema=None) as batch_op:
        batch_op.create_index('idx_forecast_medicine_district_date', ['medicine_id', 'district_id', 'forecast_date'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicine_forecast_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_forecast_forecast_date'), ['forecast_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_forecast_medicine_id'), ['medicine_id'], unique=False)

    op.create_table('medicine_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine_sales', schema=None) as batch_op:
        batch_op.create_index('idx_medicine_district_date', ['medicine_id', 'district_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_sales_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_sales_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicine_sales_medicine_id'), ['medicine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_sales_medicine_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_sales_district_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_sales_date'))
        batch_op.drop_index('idx_medicine_district_date')

    op.drop_table('medicine_sales')
    with op.batch_alter_table('medicine_forecast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_forecast_medicine_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_forecast_forecast_date'))
        batch_op.drop_index(batch_op.f('ix_medicine_forecast_district_id'))
        batch_op.drop_index('idx_forecast_medicine_district_date')

    op.drop_table('medicine_forecast')
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_formula_id'))
        batch_op.drop_index(batch_op.f('ix_medicine_brand_name'))

    op.drop_table('medicine')
    with op.batch_alter_table('formula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formula_name'))

    op.drop_table('formula')
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_name'))

    op.drop_table('district')
    # ### end Alembic commands ###
