"""Add weather_data table for forecast integration

Revision ID: 71bc2434bdfe
Revises: 78cc22930cb9
Create Date: 2025-12-13 04:20:03.150135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bc2434bdfe'
down_revision = '78cc22930cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('apparent_temperature_max', sa.Float(), nullable=True),
    sa.Column('apparent_temperature_min', sa.Float(), nullable=True),
    sa.Column('apparent_temperature_mean', sa.Float(), nullable=True),
    sa.Column('relative_humidity_2m_mean', sa.Float(), nullable=True),
    sa.Column('relative_humidity_2m_max', sa.Float(), nullable=True),
    sa.Column('relative_humidity_2m_min', sa.Float(), nullable=True),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_data_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_data_date'))

    op.drop_table('weather_data')
    # ### end Alembic commands ###
