"""Remove district_id from medicine table

Revision ID: a63da9aa5d02
Revises: c67b9a1d3dfd
Create Date: 2025-12-17 01:56:21.834637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a63da9aa5d02'
down_revision = 'c67b9a1d3dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_district_id'))
        batch_op.drop_column('district_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_medicine_district_id'), ['district_id'], unique=False)

    # ### end Alembic commands ###
