"""Remove composite constraint and allow null district_id

Revision ID: c67b9a1d3dfd
Revises: edc996c81a16
Create Date: 2025-12-17 01:45:06.224647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c67b9a1d3dfd'
down_revision = 'edc996c81a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        # Make district_id nullable
        batch_op.alter_column('district_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        # Drop the composite unique constraint (it's both an index and constraint)
        batch_op.drop_constraint('uq_district_medicine', type_='unique')
        # Create a unique constraint on medicine_id alone
        batch_op.create_unique_constraint('uq_medicine_id', ['medicine_id'])

    with op.batch_alter_table('medicine_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_sales_medicine_id'), ['medicine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_sales_medicine_id'))

    with op.batch_alter_table('medicine', schema=None) as batch_op:
        # Restore the composite unique constraint
        batch_op.drop_constraint('uq_medicine_id', type_='unique')
        batch_op.create_unique_constraint('uq_district_medicine', ['district_id', 'medicine_id'])
        # Make district_id non-nullable again
        batch_op.alter_column('district_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
