"""Remove confidence_level from medicine_forecast

Revision ID: d2a4daca6c7f
Revises: 35d3fd326cf2
Create Date: 2025-12-17 02:35:30.418015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2a4daca6c7f'
down_revision = '35d3fd326cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_forecast', schema=None) as batch_op:
        batch_op.drop_column('confidence_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_forecast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_level', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
