"""Add district_id and therapeutic_class to medicine

Revision ID: edc996c81a16
Revises: 6846b65a5b25
Create Date: 2025-12-17 01:21:39.244085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc996c81a16'
down_revision = '6846b65a5b25'
branch_labels = None
depends_on = None


def upgrade():
    # Add columns as nullable first
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('therapeutic_class', sa.String(length=100), nullable=True))
    
    # Update existing medicines to use the first district
    conn = op.get_bind()
    first_district = conn.execute(sa.text("SELECT id FROM district LIMIT 1")).fetchone()
    if first_district:
        conn.execute(
            sa.text("UPDATE medicine SET district_id = :district_id WHERE district_id IS NULL"),
            {"district_id": first_district[0]}
        )
    
    # Now make district_id non-nullable and add constraints
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column('district_id', nullable=False)
        batch_op.drop_index(batch_op.f('medicine_id'))
        batch_op.create_index(batch_op.f('ix_medicine_district_id'), ['district_id'], unique=False)
        batch_op.create_unique_constraint('uq_district_medicine', ['district_id', 'medicine_id'])
        batch_op.create_foreign_key(None, 'district', ['district_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_district_medicine', type_='unique')
        batch_op.drop_index(batch_op.f('ix_medicine_district_id'))
        batch_op.create_index(batch_op.f('medicine_id'), ['medicine_id'], unique=True)
        batch_op.drop_column('therapeutic_class')
        batch_op.drop_column('district_id')

    # ### end Alembic commands ###
